// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "ocp43"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocp43.icds.online"

// Base domain from which the cluster domain is a subdomain.
base_domain = "icds.online"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "vra76-vcsa.icds.online"

// User on the vSphere server.
vsphere_user = "administrator@vsphere.local"

// Password of the user on the vSphere server.
vsphere_password = "pM0dularc!"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "Cluster"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "Datacenter"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "iscsi"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "rhcos-4.3.0-x86_64-vmware"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "192.168.68.0/23"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 2

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://192.168.68.76:8080/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.ocp43.icds.online:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWE1jRWJpcFZ3WUF3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURNd01USXlNRFl4T1ZvWApEVE13TURJeU56SXlNRFl4T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwRGJ2R2JPb3M2QXAKVFpoTElvRXY5S2ZZMndhRnB0UlZNcmgzSmdJZlFUaHU5aDUvcnpyekJmSXdpcmUySkxNaVgxRkF0ZWt1SmFwRApXOG5xMHRpSDZMM3JPdlZpV0tpNHVvWC9SY3VPMU1MUnVOV0dQS0haNyt3M3hLaTdZMTZFVkwrZ2ZLREppQXZiCmxSOW9LRkxLK3RFMUtWNU5Zdm5yRTU4WjM4MkxiMzFBL0lweDhMUHhXK2tiR0dpUllZbnVZVDlXKytMSlFoV3gKREs5aTR3ODhXczlWcFlMSXpFOW9DZTFxK2xOYy85YUpLbDRvSTI0OVhydmJxOElRMXBIK2RSTUdZWXMwOUJKMwowOGh2a2E1cnFtM1gxaHMrNndLNnNoNXF1eXVNYlYrSHBNMnpqRzFjLzlrRElHLzhiMmpFR3c1SXptNll3OStrClJlOUtEVUtCR3dJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWUvdmgzd054UWw2bGQreGh4cEdsRDF5dnhFMHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURBUzJIL0hrN2FSWkJPWWxkcGJxaTBzdStHemJqcERFWkN6OUVhZTRwTVpSOFl3VnA1bGxQT0M5UXpFClBaS0FwbUJqN0ZGVjZMRkMwQlNEYmhjdk91eFhlUnFvOFpxMG9naXpnck5pUDhDYU5POGZxTG9iOXNucUNlSEoKNHA0bnh0UnZRaHM5R2VUb1ZWSGJsUnZwVjJqN25Id0U2WkRIM3RQa2FDSzdMK3NjWEVXZ3FUaDJBczdhMmNVYgp4alN2YTZIZ0lyWjZZc3ZIWURwVWErQkY3TTNVUGwxSVpScEZvOGs3a2ZjQVFtUFVERUVmU0UycUUwb1p2T2ROCmRUTHlBQlh5RURmenY1U1ErWHZaeHlXYXFqaVcxNVhvQ2poUkJvazAzWDd2alZjdVllSHY0RWNHc2prV2dUajYKcU92ZzlPOUhiaEZDNTBZNmRIUHF2Mll1RG9jPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.ocp43.icds.online:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJWE1jRWJpcFZ3WUF3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURNd01USXlNRFl4T1ZvWApEVE13TURJeU56SXlNRFl4T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwRGJ2R2JPb3M2QXAKVFpoTElvRXY5S2ZZMndhRnB0UlZNcmgzSmdJZlFUaHU5aDUvcnpyekJmSXdpcmUySkxNaVgxRkF0ZWt1SmFwRApXOG5xMHRpSDZMM3JPdlZpV0tpNHVvWC9SY3VPMU1MUnVOV0dQS0haNyt3M3hLaTdZMTZFVkwrZ2ZLREppQXZiCmxSOW9LRkxLK3RFMUtWNU5Zdm5yRTU4WjM4MkxiMzFBL0lweDhMUHhXK2tiR0dpUllZbnVZVDlXKytMSlFoV3gKREs5aTR3ODhXczlWcFlMSXpFOW9DZTFxK2xOYy85YUpLbDRvSTI0OVhydmJxOElRMXBIK2RSTUdZWXMwOUJKMwowOGh2a2E1cnFtM1gxaHMrNndLNnNoNXF1eXVNYlYrSHBNMnpqRzFjLzlrRElHLzhiMmpFR3c1SXptNll3OStrClJlOUtEVUtCR3dJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWUvdmgzd054UWw2bGQreGh4cEdsRDF5dnhFMHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURBUzJIL0hrN2FSWkJPWWxkcGJxaTBzdStHemJqcERFWkN6OUVhZTRwTVpSOFl3VnA1bGxQT0M5UXpFClBaS0FwbUJqN0ZGVjZMRkMwQlNEYmhjdk91eFhlUnFvOFpxMG9naXpnck5pUDhDYU5POGZxTG9iOXNucUNlSEoKNHA0bnh0UnZRaHM5R2VUb1ZWSGJsUnZwVjJqN25Id0U2WkRIM3RQa2FDSzdMK3NjWEVXZ3FUaDJBczdhMmNVYgp4alN2YTZIZ0lyWjZZc3ZIWURwVWErQkY3TTNVUGwxSVpScEZvOGs3a2ZjQVFtUFVERUVmU0UycUUwb1p2T2ROCmRUTHlBQlh5RURmenY1U1ErWHZaeHlXYXFqaVcxNVhvQ2poUkJvazAzWDd2alZjdVllSHY0RWNHc2prV2dUajYKcU92ZzlPOUhiaEZDNTBZNmRIUHF2Mll1RG9jPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION

// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
// ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
// ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "192.168.68.79"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
control_plane_ips = ["192.168.68.80", "192.168.68.81", "192.168.68.82"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = ["192.168.68.88", "192.168.68.89"]

